# Generated by Django 5.1.3 on 2024-11-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Orders',
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'Orders'},
        ),
    ]
